// 미국 주요 종목 티커 → 한국어 통용명.
// 용도: 종목 검색 자동완성에서 (1) 영문 결과에 한국어명 표시, (2) 한글 입력으로 검색.
// "미국 티커 → 한국어명"을 주는 API가 없어 정적 큐레이션으로 관리(사용자 요청).
//   - 13F의 krName과 동일한 성격(수기 매핑).
//   - 새 종목은 여기에 한 줄씩 추가하면 됨. 오타(잘못된 매핑)에 주의.
//   - 미커버 티커는 한국어명만 안 붙을 뿐, 영문 검색은 정상 동작(graceful).
export const TICKER_KR: Record<string, string> = {
  // 빅테크 / 반도체 / 소프트웨어
  AAPL: '애플',
  MSFT: '마이크로소프트',
  GOOGL: '알파벳(구글)',
  GOOG: '알파벳(구글)',
  AMZN: '아마존',
  NVDA: '엔비디아',
  META: '메타(페이스북)',
  TSLA: '테슬라',
  AVGO: '브로드컴',
  ORCL: '오라클',
  CRM: '세일즈포스',
  ADBE: '어도비',
  AMD: '에이엠디(AMD)',
  INTC: '인텔',
  QCOM: '퀄컴',
  TXN: '텍사스인스트루먼트',
  MU: '마이크론',
  ARM: '암(ARM)',
  PLTR: '팔란티어',
  NFLX: '넷플릭스',
  CSCO: '시스코',
  IBM: '아이비엠(IBM)',
  NOW: '서비스나우',
  SHOP: '쇼피파이',
  UBER: '우버',
  ABNB: '에어비앤비',
  SNOW: '스노우플레이크',
  COIN: '코인베이스',
  SMCI: '슈퍼마이크로컴퓨터',
  DELL: '델',
  MSTR: '마이크로스트래티지',
  SOFI: '소파이',
  SQ: '블록(스퀘어)',
  PYPL: '페이팔',
  LRCX: '램리서치',
  KLAC: 'KLA',
  AMAT: '어플라이드머티어리얼즈',
  MRVL: '마벨',
  ON: '온세미컨덕터',
  ASML: 'ASML',
  TSM: 'TSMC(대만 반도체)',
  BABA: '알리바바',
  NIO: '니오',
  PDD: '핀둬둬',

  // 금융
  'BRK.B': '버크셔 해서웨이',
  JPM: 'JP모건',
  BAC: '뱅크오브아메리카',
  WFC: '웰스파고',
  GS: '골드만삭스',
  MS: '모건스탠리',
  V: '비자',
  MA: '마스터카드',
  AXP: '아메리칸익스프레스',
  BLK: '블랙록',

  // 소비재 / 유통
  KO: '코카콜라',
  PEP: '펩시코',
  MCD: '맥도날드',
  SBUX: '스타벅스',
  NKE: '나이키',
  DIS: '디즈니',
  COST: '코스트코',
  WMT: '월마트',
  HD: '홈디포',
  TGT: '타겟',
  LULU: '룰루레몬',
  PG: '프록터앤드갬블',
  PM: '필립모리스',

  // 헬스케어
  JNJ: '존슨앤드존슨',
  PFE: '화이자',
  MRNA: '모더나',
  LLY: '일라이릴리',
  UNH: '유나이티드헬스',
  ABBV: '애브비',
  MRK: '머크',
  NVO: '노보노디스크',

  // 산업재 / 에너지 / 자동차
  XOM: '엑슨모빌',
  CVX: '셰브론',
  BA: '보잉',
  CAT: '캐터필러',
  GE: '제너럴일렉트릭(GE)',
  LMT: '록히드마틴',
  F: '포드',
  GM: '제너럴모터스',
  RIVN: '리비안',
  LCID: '루시드',

  // 통신
  'T': 'AT&T',
  VZ: '버라이즌',

  // 한국 개인투자자 다빈도 ETF
  SPY: 'S&P500 ETF',
  VOO: 'S&P500 ETF(뱅가드)',
  QQQ: '나스닥100 ETF',
  QQQM: '나스닥100 ETF',
  SCHD: '미국 배당 ETF',
  JEPI: 'JEPI 커버드콜 ETF',
  JEPQ: 'JEPQ 커버드콜 ETF',
  TQQQ: '나스닥100 3배 ETF',
  SOXL: '반도체 3배 ETF',
  SOXX: '반도체 ETF',
  SMH: '반도체 ETF',
  DIA: '다우존스 ETF',
  VTI: '미국 전체시장 ETF',

  // === 2026-06 확장 (StockSymbol 테이블 영문명과 교차검증) ===
  // 반도체/하드웨어
  ADI: '아날로그디바이스',
  MCHP: '마이크로칩',
  NXPI: 'NXP반도체',
  MPWR: '모놀리식파워',
  TER: '테라다인',
  ENTG: '엔테그리스',
  COHR: '코히런트',
  WOLF: '울프스피드',
  SWKS: '스카이웍스',
  QRVO: '코보',
  GFS: '글로벌파운드리스',
  ANET: '아리스타네트웍스',
  WDC: '웨스턴디지털',
  SNDK: '샌디스크',
  STX: '시게이트',
  NTAP: '넷앱',
  HPE: '휴렛팩커드엔터프라이즈',
  HPQ: 'HP',
  GLW: '코닝',
  CRWV: '코어위브',
  NBIS: '네비우스',
  APLD: '어플라이드디지털',
  IREN: '아이렌',
  // SW/인터넷
  INTU: '인튜이트',
  WDAY: '워크데이',
  TEAM: '아틀라시안',
  HUBS: '허브스팟',
  ZM: '줌',
  DOCU: '도큐사인',
  TWLO: '트윌리오',
  OKTA: '옥타',
  MDB: '몽고DB',
  DDOG: '데이터독',
  NET: '클라우드플레어',
  ZS: '지스케일러',
  CRWD: '크라우드스트라이크',
  PANW: '팔로알토네트웍스',
  FTNT: '포티넷',
  S: '센티넬원',
  GTLB: '깃랩',
  ESTC: '일래스틱',
  PATH: '유아이패스',
  AI: 'C3.ai',
  BBAI: '빅베어AI',
  SOUN: '사운드하운드AI',
  TTD: '더트레이드데스크',
  RBLX: '로블록스',
  U: '유니티',
  DKNG: '드래프트킹스',
  RDDT: '레딧',
  SNAP: '스냅',
  PINS: '핀터레스트',
  SPOT: '스포티파이',
  DASH: '도어대시',
  ROKU: '로쿠',
  ETSY: '엣시',
  CHWY: '츄이',
  CART: '인스타카트',
  W: '웨이페어',
  CVNA: '카바나',
  // 양자/우주/방산/원자력
  IONQ: '아이온큐',
  RGTI: '리게티컴퓨팅',
  QBTS: '디웨이브퀀텀',
  QUBT: '퀀텀컴퓨팅',
  RKLB: '로켓랩',
  ASTS: 'AST스페이스모바일',
  LUNR: '인튜이티브머신스',
  SPCE: '버진갤럭틱',
  RDW: '레드와이어',
  PL: '플래닛랩스',
  JOBY: '조비에비에이션',
  ACHR: '아처에비에이션',
  RTX: 'RTX',
  NOC: '노스럽그루먼',
  GD: '제너럴다이내믹스',
  LHX: 'L3해리스',
  HII: '헌팅턴잉걸스',
  KTOS: '크라토스',
  AVAV: '에어로바이론먼트',
  LDOS: '레이도스',
  OKLO: '오클로',
  SMR: '뉴스케일파워',
  NNE: '나노뉴클리어에너지',
  LEU: '센트루스에너지',
  CCJ: '카메코',
  UEC: '우라늄에너지',
  UUUU: '에너지퓨얼스',
  NXE: '넥스젠에너지',
  // 에너지/전력/클린
  VST: '비스트라',
  CEG: '컨스텔레이션에너지',
  GEV: 'GE버노바',
  TLN: '탈렌에너지',
  NRG: 'NRG에너지',
  NEE: '넥스트에라에너지',
  DUK: '듀크에너지',
  SO: '서던컴퍼니',
  D: '도미니언에너지',
  AEP: '아메리칸일렉트릭파워',
  EXC: '엑셀론',
  SRE: '셈프라',
  FSLR: '퍼스트솔라',
  ENPH: '엔페이즈에너지',
  SEDG: '솔라엣지',
  RUN: '선런',
  PLUG: '플러그파워',
  BE: '블룸에너지',
  BLDP: '발라드파워',
  FCEL: '퓨얼셀에너지',
  QS: '퀀텀스케이프',
  CHPT: '차지포인트',
  EVGO: '이브이고',
  ALB: '앨버말',
  MP: 'MP머티리얼즈',
  LAC: '리튬아메리카스',
  COP: '코노코필립스',
  EOG: 'EOG리소스',
  SLB: '슐럼버거',
  OXY: '옥시덴탈페트롤리엄',
  PSX: '필립스66',
  MPC: '마라톤페트롤리엄',
  VLO: '발레로에너지',
  KMI: '킨더모건',
  WMB: '윌리엄스',
  OKE: '원오크',
  LNG: '셰니어에너지',
  // 핀테크/금융
  NU: '누홀딩스',
  PGY: '파가야',
  AFRM: '어펌',
  UPST: '업스타트',
  HOOD: '로빈후드',
  LC: '렌딩클럽',
  BILL: '빌닷컴',
  TOST: '토스트',
  MQ: '마르케타',
  FOUR: '쉬프트4',
  GPN: '글로벌페이먼츠',
  FIS: 'FIS',
  C: '씨티그룹',
  USB: 'US뱅코프',
  PNC: 'PNC파이낸셜',
  TFC: '트루이스트',
  SCHW: '찰스슈왑',
  COF: '캐피탈원',
  ALLY: '앨라이파이낸셜',
  SPGI: 'S&P글로벌',
  MCO: '무디스',
  ICE: '인터컨티넨탈익스체인지',
  CME: 'CME그룹',
  NDAQ: '나스닥',
  MSCI: 'MSCI',
  PGR: '프로그레시브',
  CB: '처브',
  AIG: 'AIG',
  MET: '메트라이프',
  PRU: '푸르덴셜',
  ALL: '올스테이트',
  TRV: '트래블러스',
  AON: '에이온',
  KKR: 'KKR',
  BX: '블랙스톤',
  APO: '아폴로글로벌',
  ARES: '아레스매니지먼트',
  OWL: '블루아울캐피탈',
  // 헬스케어/바이오
  ABT: '애벗래버러토리스',
  TMO: '써모피셔',
  DHR: '다나허',
  BMY: '브리스톨마이어스스큅',
  AMGN: '암젠',
  GILD: '길리어드',
  REGN: '리제네론',
  VRTX: '버텍스',
  BIIB: '바이오젠',
  ISRG: '인튜이티브서지컬',
  DXCM: '덱스컴',
  MDT: '메드트로닉',
  SYK: '스트라이커',
  BSX: '보스턴사이언티픽',
  EW: '에드워즈라이프사이언스',
  ZTS: '조에티스',
  IDXX: '아이덱스',
  IQV: '아이큐비아',
  HCA: 'HCA헬스케어',
  CI: '시그나',
  CVS: 'CVS헬스',
  HUM: '휴매나',
  ELV: '엘레반스헬스',
  MCK: '맥케슨',
  ZBH: '짐머바이오메트',
  BDX: '벡톤디킨슨',
  GEHC: 'GE헬스케어',
  RMD: '레스메드',
  A: '애질런트',
  CRSP: '크리스퍼테라퓨틱스',
  NTLA: '인텔리아테라퓨틱스',
  BEAM: '빔테라퓨틱스',
  NVAX: '노바백스',
  VKTX: '비킹테라퓨틱스',
  HIMS: '힘스앤허스',
  TEM: '템퍼스AI',
  RXRX: '리커전',
  // 중국 ADR / 동남아
  JD: '징둥닷컴',
  BIDU: '바이두',
  NTES: '넷이즈',
  BILI: '빌리빌리',
  LI: '리오토',
  XPEV: '샤오펑',
  TME: '텐센트뮤직',
  FUTU: '푸투홀딩스',
  TIGR: '타이거브로커스',
  BEKE: '베이커',
  TCOM: '트립닷컴',
  ZTO: 'ZTO익스프레스',
  EDU: '신동방',
  SE: '씨리미티드',
  GRAB: '그랩',
  MELI: '메르카도리브레',
  CPNG: '쿠팡',
  // 소비재/유통
  LOW: '로우스',
  TJX: 'TJX',
  ROST: '로스스토어스',
  DG: '달러제너럴',
  DLTR: '달러트리',
  ULTA: '울타뷰티',
  BBY: '베스트바이',
  YUM: '얌브랜즈',
  CMG: '치폴레',
  DPZ: '도미노피자',
  QSR: '레스토랑브랜즈',
  MAR: '메리어트',
  HLT: '힐튼',
  BKNG: '부킹홀딩스',
  EXPE: '익스피디아',
  RCL: '로열캐리비안',
  CCL: '카니발',
  NCLH: '노르위지안크루즈',
  LVS: '라스베가스샌즈',
  WYNN: '윈리조트',
  MGM: 'MGM리조트',
  CZR: '시저스엔터테인먼트',
  DECK: '데커스아웃도어',
  ONON: '온홀딩',
  CROX: '크록스',
  RL: '랄프로렌',
  VFC: 'VF코퍼레이션',
  TPR: '태피스트리',
  EL: '에스티로더',
  ELF: '엘프뷰티',
  CELH: '셀시어스',
  MNST: '몬스터음료',
  KDP: '큐리그닥터페퍼',
  KHC: '크래프트하인즈',
  MDLZ: '몬델리즈',
  GIS: '제너럴밀스',
  HSY: '허쉬',
  CL: '콜게이트',
  KMB: '킴벌리클라크',
  CLX: '클로락스',
  KVUE: '켄뷰',
  CHD: '처치앤드와이트',
  SYY: '시스코',
  KR: '크로거',
  MO: '알트리아',
  STZ: '컨스텔레이션브랜즈',
  TAP: '몰슨쿠어스',
  // 산업재/소재
  HON: '허니웰',
  UPS: 'UPS',
  FDX: '페덱스',
  DE: '디어',
  MMM: '쓰리엠',
  EMR: '에머슨일렉트릭',
  ETN: '이튼',
  PH: '파커하니핀',
  ITW: '일리노이툴웍스',
  CMI: '커민스',
  PCAR: '팩카',
  GWW: 'WW그레인저',
  FAST: '패스널',
  URI: '유나이티드렌탈스',
  RSG: '리퍼블릭서비스',
  WM: '웨이스트매니지먼트',
  JCI: '존슨컨트롤스',
  CARR: '캐리어글로벌',
  OTIS: '오티스',
  PWR: '콴타서비스',
  LIN: '린데',
  SHW: '셔윈윌리엄스',
  APD: '에어프로덕츠',
  ECL: '에코랩',
  FCX: '프리포트맥모란',
  NEM: '뉴몬트',
  NUE: '뉴코어',
  DOW: '다우',
  DD: '듀폰',
  CTVA: '코르테바',
  // 통신/미디어
  TMUS: 'T모바일',
  CMCSA: '컴캐스트',
  CHTR: '차터커뮤니케이션스',
  WBD: '워너브라더스디스커버리',
  FOXA: '폭스',
  NWSA: '뉴스코퍼레이션',
  EA: '일렉트로닉아츠',
  TTWO: '테이크투',
  // REIT
  AMT: '아메리칸타워',
  PLD: '프로로지스',
  EQIX: '에퀴닉스',
  O: '리얼티인컴',
  SPG: '사이먼프로퍼티',
  PSA: '퍼블릭스토리지',
  CCI: '크라운캐슬',
  DLR: '디지털리얼티',
  WELL: '웰타워',
  VICI: '비치프로퍼티스',
  IRM: '아이언마운틴',
  // 밈/기타
  GME: '게임스톱',
  AMC: 'AMC엔터테인먼트',
  BB: '블랙베리',
  NOK: '노키아',
  LYFT: '리프트',
  RKT: '로켓컴퍼니',
  // 크립토 관련
  MARA: '마라홀딩스',
  RIOT: '라이엇플랫폼스',
  CLSK: '클린스파크',
  HUT: '헛8마이닝',
  WULF: '테라울프',
  CIFR: '사이퍼마이닝',
  CORZ: '코어사이언티픽',
  // ETF (추가)
  IVV: 'S&P500 ETF(아이셰어즈)',
  IWM: '러셀2000 ETF',
  VUG: '미국 성장주 ETF',
  VTV: '미국 가치주 ETF',
  SCHG: '미국 대형성장주 ETF',
  VYM: '미국 고배당 ETF',
  XLK: '미국 기술섹터 ETF',
  XLF: '미국 금융섹터 ETF',
  XLE: '미국 에너지섹터 ETF',
  XLV: '미국 헬스케어섹터 ETF',
  TLT: '미국 장기국채 ETF',
  IEF: '미국 중기국채 ETF',
  GLD: '금 ETF',
  SLV: '은 ETF',
  IAU: '금 ETF(아이셰어즈)',
  ARKK: '아크 이노베이션 ETF',
  IBIT: '비트코인 현물 ETF(블랙록)',
  FBTC: '비트코인 현물 ETF(피델리티)',
  TSLL: '테슬라 2배 ETF',
  NVDL: '엔비디아 2배 ETF',
  SQQQ: '나스닥100 3배 인버스 ETF',
  SOXS: '반도체 3배 인버스 ETF',
  FNGU: 'FANG+ 3배 ETF',
  UPRO: 'S&P500 3배 ETF',
  SPXL: 'S&P500 3배 ETF(Direxion)',
};

// 티커 → 한국어명 (없으면 undefined).
export function krNameOf(symbol: string): string | undefined {
  return TICKER_KR[symbol.toUpperCase()];
}

// 한글 입력(부분일치)으로 매칭되는 티커 목록. 영문 입력은 Finnhub가 처리하므로
// 한글이 포함된 쿼리에서만 동작.
export function searchKrTickers(query: string): string[] {
  const q = query.trim();
  if (!q || !/[가-힣]/.test(q)) return [];
  return Object.entries(TICKER_KR)
    .filter(([, kr]) => kr.includes(q))
    .map(([ticker]) => ticker);
}
